---
title: "Chemokine signaling pathway"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
rm(list = ls(all.names = TRUE)) # Clear all memory
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(KEGGgraph)
library(KEGG.db)
library(KEGGREST)
library(gage)
library("readxl")
library(dplyr)

data(kegg.gs)
data(kegg.gs.dise)



```

```{r}

diff_expressed <- read_excel("C:/Users/admin/Desktop/gse_16357_001.xlsx")
diff_expressed <- diff_expressed$gse16357_entrez

#diff_expressed <- read_excel("C:/Users/admin/Desktop/experiment.xlsx")
#diff_expressed <- diff_expressed$gse16357

diff_expressed <- as.vector(diff_expressed)

diff_expressed <- diff_expressed[-grep("/+", diff_expressed)]

```


```{r}
all_KEGG_pathways <- append(kegg.gs, kegg.gs.dise)
list_intersected_genes <- lapply(all_KEGG_pathways, function(x) intersect(diff_expressed, x))

short_list <- list_intersected_genes[lengths(list_intersected_genes) >= 5]
pathids <- substr(names(short_list), start=4, stop=8)

graph_list <- lapply(pathids, function(hsa_name){
  mapkG <- try(
  {
    tmp <- tempfile()
    print(hsa_name)
    retrieveKGML(hsa_name, organism="hsa", destfile = tmp, method="internal", quiet=TRUE)
    mapkG <- parseKGML2Graph(tmp,expandGenes=T)
    mapkG
  })  
})
ok_graphs <- sapply(graph_list, function(x) typeof(x) == "S4")
graph_list <- graph_list[ok_graphs]
mega_graph <- mergeKEGGgraphs(graph_list)

```

```{r}
mega_nodes <- nodes(mega_graph)
mega_edges <- edges(mega_graph)

symbol_names <- sapply(mega_nodes, function(x) getKEGGnodeData(mega_graph,x)@graphics@name)
hsa_names <- sapply(mega_nodes, function(x) getKEGGnodeData(mega_graph,x)@name)

unique_symbol_names <- unique(unname(symbol_names))
```

```{r Make dictionary}
dict_hsa_to_symb = c()

for(k in 1:length(symbol_names)){
  current_hsa <- sapply(hsa_names[[k]], function(x) substr(x,start = 5, stop = nchar(x)))
  #current_hsa <- sapply(hsa_names[[k]], function(x) translateKEGGID2GeneID(x))
  current_symbol <- rep(symbol_names[k],length(current_hsa))
  names(current_symbol) <- current_hsa
  dict_hsa_to_symb <- c(dict_hsa_to_symb, current_symbol)
}

diff_expressed_gene_symb <- dict_hsa_to_symb[diff_expressed]
diff_expressed_gene_symb <-unique(unname(diff_expressed_gene_symb[!is.na(diff_expressed_gene_symb)]))
```

```{r First-level neighbours}

forward_edges_list <- vector("list", length(unique_symbol_names))
names(forward_edges_list) <- unique_symbol_names

counter <- 0
for (node_name in attributes(mega_edges)$`names`){
  counter <- counter + 1
  print(counter)
  disp_node_name <- getKEGGnodeData(mega_graph,node_name)@graphics@name
  print(disp_node_name)
  
  current_isoform_children <- unname(sapply(mega_edges[[node_name]], 
                                            function(x) getKEGGnodeData(mega_graph,x)@graphics@name))
  if(length(current_isoform_children)!=0){
    forward_edges_list[[disp_node_name]] <- union(forward_edges_list[[disp_node_name]],
                                                  current_isoform_children)  
  }
}
forward_edges_list <- forward_edges_list[lapply(forward_edges_list,length)>0]

```

```{r All neighbours}
gene_iterator_forward <- function(goal_gene){
  print(goal_gene)
  flag_visited <- rep(0,length(unique_symbol_names))
  names(flag_visited) <- unique_symbol_names
  
  all_children <- forward_edges_list[[goal_gene]]
  
  flag_visited[all_children] <- 1
  counter <- 1
  
  while (counter <= length(all_children)) {
    current_child <- all_children[counter]
    children_of_this_child <<- forward_edges_list[[current_child]]

    for_children_to_add <<- names(which(flag_visited[children_of_this_child] == 0))

    all_children <- c(all_children, for_children_to_add)
    
    flag_visited[for_children_to_add] <- 1
    counter <- counter + 1

  }
  all_children <- intersect(all_children, diff_expressed_gene_symb)
  all_children <- union(all_children, goal_gene)
  return (all_children)
}

all_children <- lapply(diff_expressed_gene_symb, gene_iterator_forward)
names(all_children) <- diff_expressed_gene_symb


```


```{r}

whomax <- names( which.max( sapply(all_children, length) ) )
main_ancestorz <- whomax
whomax_descendants <- length(all_children[[whomax]]) 
while( whomax_descendants > 0 ){
  all_children <- sapply(all_children, function(x) setdiff(x,all_children[[whomax]]))
  whomax <- names( which.max( sapply(all_children, length) ) )
  main_ancestorz <- c(main_ancestorz, whomax)
  whomax_descendants <- length(all_children[[whomax]]) 
}

print(main_ancestorz)

```

